@startuml PC-Komponenten-Architektur

left to right direction

actor RESTClient
actor GraphQLClient

node "Nest" {
  [RequestLoggerMiddleware]

  [PcController]
  [PcResolver]

  [PcService]
  [PcWriteService]

  [PrismaClient]

  [MailService]
}


cloud {
    [Prisma]
}

cloud {
    [nest-keycloak-connect]
}

cloud {
    [nodemailer]
}

database "DB pc_komponenten" {
    [Tabelle komponente]
    [Tabelle spezifikation]
    [Tabelle hersteller]
}

node {
    [Keycloak]
}

node {
    [Mailserver]
}

RESTClient ~~> [RequestLoggerMiddleware]
GraphQLClient ~~> [RequestLoggerMiddleware]

[RequestLoggerMiddleware] ~~> [PcController]
[RequestLoggerMiddleware] ~~> [PcResolver]

[PcController] ..> [PcService]
[PcWriteController] ..> [PcWriteService]
[PcResolver] ..> [PcService]
[PcResolver] ..> [PcWriteService]

[PcService] ..> [PrismaClient]
[PcWriteService] ..> [PrismaClient]
[PcWriteService] ..> [MailService]

[PrismaClient] ~~> [Prisma]
[Prisma] ~~> [Tabelle komponente]
[Prisma] ~~> [Tabelle spezifikation]
[Prisma] ~~> [Tabelle hersteller]

[PcController] ...> [nest-keycloak-connect]
[PcResolver] ...> [nest-keycloak-connect]
[nest-keycloak-connect] ~~> [Keycloak]
[MailService] ~~> [nodemailer]
[nodemailer] ~~> [Mailserver]

@enduml