@startuml Controller-Klasse
interface Promise<T>

package @nestjs/graphql {
  annotation Resolver
  annotation UseGuards
  annotation UseInterceptors
  annotation Mutation
  annotation Args
}

package nest-keycloak-connect {
  class AuthGuard
  annotation Roles
}

package pc #DDDDDD {
  package service #FFFFFF {
    class PcWriteService << control >>
  }

  class PcDtoOhneRef << entity >>
  class PcDTO << entity >>
  PcDtoOhneRef <|-- PcDTO

  interface IdInput {
      id: number
  }

  class PcMutationResolver << control >> << @Resolver() >> << @UseGuards() >> << @UseInterceptors() >> {
    + @Mutation() @Roles() async create(@Args() pcDTO: PcDTO): Promise<number>
    + @Mutation() @Roles() async update(@Args() pcDTO: PcDtoOhneRef): Promise<number>
    + @Mutation() @Roles() async delete(@Args() id: IdInput): Promise<boolean>
  }

  PcMutationResolver o-down-> "1" PcWriteService : service
  PcMutationResolver ..> PcDTO
  PcMutationResolver ..> PcDtoOhneRef
  PcMutationResolver ..> IdInput
  PcMutationResolver .up.> Promise
  PcMutationResolver .up.> Resolver
  PcMutationResolver .up.> AuthGuard
  PcMutationResolver .up.> Roles
}
@enduml