@startuml Controller-Klasse
interface Promise<T>
interface Readonly<T>

package @nestjs/graphql {
  annotation Resolver
  annotation UseInterceptors
  annotation Query
  annotation Args
}

package generated.prisma {
  class Prisma
  class KomponenteGetPayload<T>
  Prisma +-- KomponenteGetPayload
}

package pc {
  package service {
    class PcService << control >>
  }

  package graphql #DDDDDD {
    class "type PcDTO = Omit<Komponente, ...>" as PcDTO
    hide PcDTO circle

    interface IdInput {
        id: number
    }

    class PcQueryResolver << control >> << @Resolver() >> << @UseInterceptors() >> {
      + @Query() async pc(@Args() id: IdInput): Promise<Readonly<KomponenteGetPayload>>
      + @Query() async pcs(@Args() name: string | undefined): Promise<PcDTO[]>
    }

    PcQueryResolver o-down-> "1" PcService : service
    PcQueryResolver ..> PcDTO
    PcQueryResolver ..> IdInput
    PcQueryResolver .up.> Resolver
    PcQueryResolver .up.> Promise
    PcQueryResolver .up.> Readonly
    PcQueryResolver .up.> KomponenteGetPayload
  }
}
@enduml