@startuml Anwendungskern
interface Promise<T>

package @nestjs/common {
  annotation Injectable
  exception NotFoundException
}

package generated.prisma {
  class Prisma
  class KomponenteCreateInput
  class KomponenteGetPayload<T>
  class KomponenteUpdateInput
  Prisma +-- KomponenteCreateInput
  Prisma +-- KomponenteGetPayload
  Prisma +-- KomponenteUpdateInput
}

package mail {
  class MailService
}

package pc {
  package service #DDDDDD {
    class PrismaService
    class PcService
    exception VersionInvalid
    exception VersionOutdated

    class PcWriteService << control >> <<@Injectable()>> {
      + async create(pc: Prisma.KomponenteCreateInput): Promise<number>
      + async update(id: number, pc: Prisma.KomponenteUpdateInput, version: string): Promise<number>
      + async delete(id: number): Promise<void>
    }

    PcWriteService o--> "1" PrismaService
    PcWriteService o--> "1" PcService: readService
    PcWriteService o--> "1" MailService: mailService
    PcWriteService .up.> Injectable
    PcWriteService .up.> NotFoundException
    PcWriteService .up.> Promise
    PcWriteService .down.> KomponenteCreateInput
    PcWriteService .down.> KomponenteGetPayload
    PcWriteService .down.> KomponenteUpdateInput
    PcWriteService .down.> VersionInvalid
    PcWriteService .down.> VersionOutdated
  }
}
@enduml