@startuml Sequenzdiagramm

actor Gast

' Teilnehmer wurden an das PC-Projekt angepasst
boundary PcController
control PcService
database pc_komponenten

' Die Abläufe bleiben gleich, aber die Teilnehmer sind neu
Gast -> PcController : GET / getById()
PcController -> PcService: findById()
PcService -> pc_komponenten: [Prisma]

footer (c) Dein Name

@enduml
