@startuml Use Cases

actor Gast
actor Admin
actor Kunde

' Das System-Rechteck wurde von "buch" auf "komponente" umbenannt
rectangle komponente {
    Gast --> (Komponente suchen)
    Admin --> (Komponente suchen)
    Admin --> (Komponente anlegen)
    Admin --> (Komponente ändern)
    Admin --> (Komponente löschen)
    Kunde --> (Komponente suchen)
    Kunde --> (Komponente anlegen)
    Kunde --> (Komponente ändern)
}

footer (c) Dein Name

@enduml
