= Projekthandbuch
Dein Name <deine.email@h-ka.de>
:doctype: book
:toc: left
:sectanchors:
:sectlinks:
:sectnums:
:source-highlighter: highlight.js
:icons: font

== Architektur

.Komponenten-Diagramm
[plantuml,architektur,svg]
----
include::architektur.plantuml[]
----

=== Controller

.\"PcController\" (Lesen)
[plantuml,PcController,svg]
----
include::PcController.plantuml[]
----

.\"PcWriteController\" (Schreiben)
[plantuml,PcWriteController,svg]
----
include::PcWriteController.plantuml[]
----

=== GraphQL Resolver

.\"PcQueryResolver\" (Lesen)
[plantuml,PcQueryResolver,svg]
----
include::PcQueryResolver.plantuml[]
----

.\"PcMutationResolver\" (Schreiben)
[plantuml,PcMutationResolver,svg]
----
include::PcMutationResolver.plantuml[]
----

=== Geschäftslogik (Services)

.\"PcService\" (Lesen)
[plantuml,PcService,svg]
----
include::PcService.plantuml[]
----

.\"PcWriteService\" (Schreiben)
[plantuml,PcWriteService,svg]
----
include::PcWriteService.plantuml[]
----

=== ER-Diagramm

.ER-Diagramm
[plantuml,ER-Diagramm_PC_Komponenten,svg]
----
include::ER-Diagramm_PC_Komponenten.plantuml[]
----

== Programmierrichtlinien für TypeScript und JavaScript

Für die Programmierung mit *TypeScript* und *JavaScript* sind folgende
Styleguides empfehlenswert:

[horizontal]
_E-Book zu TypeScript_:: https://github.com/gibbok/typescript-book
_Google_:: https://google.github.io/styleguide/tsguide.html
_Airbnb_:: https://github.com/airbnb/javascript
_Shopify_:: https://github.com/Shopify/javascript
_React bei Airbnb_:: https://github.com/airbnb/javascript/tree/master/react
_Angular_:: https://angular.io/docs/ts/latest/guide/style-guide.html
_Microsoft_:: https://github.com/Microsoft/TypeScript/wiki/Coding-guidelines

Von IBM und Red Hat gibt es bei GitHub _Node.js Reference Architecture_
https://github.com/nodeshift/nodejs-reference-architecture, wo alle möglichen
Aspekte bei der Softwareentwicklung mit Node berücksichtigt sind und
entsprechende Empfehlungen bzw. Best Practices beschrieben sind.
Diese Dokumentation muss man einfach gelesen haben. Ebenfalls empfehlenswert
ist https://github.com/goldbergyoni/nodebestpractices.
